version: '3.3'

services:

  database:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "empik"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
